name: Build and release

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download fonts
        run: |
          # Source Han Serif
          wget -q -P ./fonts/ https://github.com/adobe-fonts/source-han-serif/raw/release/OTF/SimplifiedChinese/SourceHanSerifSC-ExtraLight.otf
          wget -q -P ./fonts/ https://github.com/adobe-fonts/source-han-serif/raw/release/OTF/SimplifiedChinese/SourceHanSerifSC-Light.otf
          wget -q -P ./fonts/ https://github.com/adobe-fonts/source-han-serif/raw/release/OTF/SimplifiedChinese/SourceHanSerifSC-Regular.otf
          wget -q -P ./fonts/ https://github.com/adobe-fonts/source-han-serif/raw/release/OTF/SimplifiedChinese/SourceHanSerifSC-Medium.otf
          wget -q -P ./fonts/ https://github.com/adobe-fonts/source-han-serif/raw/release/OTF/SimplifiedChinese/SourceHanSerifSC-SemiBold.otf
          wget -q -P ./fonts/ https://github.com/adobe-fonts/source-han-serif/raw/release/OTF/SimplifiedChinese/SourceHanSerifSC-Bold.otf
          wget -q -P ./fonts/ https://github.com/adobe-fonts/source-han-serif/raw/release/OTF/SimplifiedChinese/SourceHanSerifSC-Heavy.otf
          # DejaVu fonts
          wget -q -P ./fonts/ https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip
          unzip -q -d ./fonts/ ./fonts/dejavu-fonts-ttf-2.37.zip
          mv ./fonts/dejavu-fonts-ttf-2.37/ttf/* ./fonts/
      - name: Get date string
        run: |
          echo "DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
      - name: Build '基于石墙控制线的存储器内的微时序特性分析及应用'
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./基于石墙控制线的存储器内的微时序特性分析及应用/
          root_file: 基于石墙控制线的存储器内的微时序特性分析及应用.tex
          latexmk_use_xelatex: true
          post_compile: |
            mv ./基于石墙控制线的存储器内的微时序特性分析及应用.pdf ${{ format('./基于石墙控制线的存储器内的微时序特性分析及应用-{0}-build-{1}.pdf', env.DATE, github.run_number) }}
      - name: Push tag
        uses: anothrNick/github-tag-action@1.36.0
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ format('build-{0}', github.run_number) }}
      - name: Release
        uses: softprops/action-gh-release@v0.1.13
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        with:
          tag_name: ${{ format('build-{0}', github.run_number) }}
          name: ${{ format('{0} build {1}', env.DATE, github.run_number) }}
          files: ./**/*.pdf
